# Use custom format
format = """
[┌───>](cyan)$hostname$username$directory$aws$gcloud$crystal$dart$dotnet$elixir$elm$erlang$golang$java$julia$nim$nodejs$php$purescript$python$ruby$rust$swift$package$git_branch$git_commit$git_state$git_status
[└](cyan)$cmd_duration[─>](cyan)$character"""

# Don't print a new line at the start of the prompt
# add_newline = false

[character]
success_symbol = "[λ](bold green) "
error_symbol = "[X](bold red) "

[username]
show_always = true

[directory]
truncation_length = 8

[directory.substitutions]
"~/Documents" = "  "
"~/Music" = "  "
"~/Movies" = "  "
"~/Pictures" = "  "
"~/Sources" = "  "
"~" = "  "

[aws]
# disabled = true
symbol = " "

[gcloud]
# disabled = true
symbol = "☁️ "

[cmake]
# disabled = true
# symbol = "卑" # alternate
symbol = "喝"

[crystal]
# disabled = true
symbol = " "

[dart]
# disabled = true
# symbol = " " # original
symbol = "﯑ " # clearer

[dotnet]
# disabled = true
symbol = " "
# style = "bg:#4A35CC fg:#EEEEEE"
heuristic = true

[elixir]
# disabled = true
symbol = " "

[elm]
# disabled = true
# symbol = " " # original
symbol = " " # clearer

[erlang]
# disabled = true
symbol = " "

[golang]
# disabled = true
symbol = " "

[java]
# disabled = true
symbol = " "

[julia]
# disabled = true
symbol = " "

[nim]
# disabled = true
symbol = " "

[nodejs]
# disabled = true
symbol = " "

[php]
# disabled = true
symbol = " "

[purescript]
# disabled = true
symbol = "<=>"

[python]
# disabled = true
symbol = " "
pyenv_prefix = "pyenv "
python_binary = "python"

[ruby]
# disabled = true
symbol = " "
# symbol = " " # alternate
style = "bg:#CC342D fg:#EEEEEE"
# format = "[[](bg:#CC342D fg:#464347)$symbol$version[](bg:#464347 fg:#CC342D)]($style)"

[rust]
# disabled = true
# symbol = " "
symbol = " " # alternate

[swift]
# disabled = true
symbol = "ﯣ "

[package]
# disabled = true
symbol = " "

[git_branch]
# disabled = true
symbol = " "
# symbol = " " # alternate
# truncation_length = 4
# truncation_symbol = ""

[git_commit]
# disabled = true
commit_hash_length = 7
# only_detached = true

[git_state]
# disabled = true
rebase = "rebasing"
merge = "merging"
revert = "reverting"
cherry_pick = " picking"
bisect = "bisecting"
am = "am'ing"
am_or_rebase = "am/rebase"
format = "[$state($progress_current/$progress_total)]($style)"

[git_status]
# disabled = true
stashed = " ${count}"
ahead = "ﲗ ${count}"
behind = "ﲔ ${count}"
diverged = "李 ${ahead_count} ${behind_count}"
conflicted = "${count}"
deleted = " ${count}"
renamed = "﫦${count}"
modified = " 凜${count}"
staged = "  ${count}"
untracked = "  ${count}"
format = "[$stashed$staged$modified$renamed$untracked$deleted$conflicted$ahead_behind]($style)"

[cmd_duration]
# disabled = true
#style = "bg:#464347 fg:#fc8c3b"
min_time = 2_000
show_milliseconds = true
show_notifications = false
min_time_to_notify = 45_000
format = "[$duration]($style)"

#format = """
#[┌───────────────────>](cyan)
#[│](cyan)$username$directory$rust$package
#[└─>](cyan)"""
